x-db-common-values:
    db-name: &db-name 'protector_test'
    db-user: &db-user 'protector'
    db-pass: &db-pass 'protector'

services:
    app:
        image: cybexwebdev/php-laravel:${DOCKER_PHP_VERSION:-8.2}-devtools
        container_name: ${COMPOSE_PROJECT_NAME}
        environment:
            CONTAINER_ROLE: web
        volumes:
            - '.:/var/package'
            - './exampleApp:/var/www/'
        env_file:
            - ./exampleApp/.env
        networks:
            - internal
            - shared
    mysql_testing:
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_DATABASE: *db-name
            MYSQL_USER: *db-user
            MYSQL_PASSWORD: *db-pass
            MYSQL_ROOT_PASSWORD: *db-pass
            MYSQL_ROOT_HOST: "%"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql:/var/lib/mysql'
        networks:
            - internal
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-pprotector" ]
            retries: 3
            timeout: 5s
    postgres_testing:
        image: 'postgres:17'
        environment:
            POSTGRES_DB: *db-name
            POSTGRES_USER: *db-user
            POSTGRES_PASSWORD: *db-pass
            POSTGRES_HOST_AUTH_METHOD: 'trust'
        volumes:
            - 'pgsql:/var/lib/postgresql/data'
        networks:
            - internal
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            retries: 3
            timeout: 5s
networks:
    internal:
        internal: true
    shared:
        external: true
volumes:
    mysql:
        driver: local
    pgsql:
        driver: local
