name: Tests

on:
    push:
        branches:
            - master
            - release/*
    pull_request:
    workflow_dispatch:

jobs:
    mysql-tests:
        name: MySQL
        uses: ./.github/workflows/tests-matrix.yml
        with:
            DATABASE_IMAGE: mysql:8.0
            DATABASE_PORT: 3306
            DATABASE_USERNAME: root
            DATABASE_CONNECTION: mysql
            DATABASE_OPTIONS: "--health-cmd=\"mysqladmin ping\" --health-interval=10s --health-timeout=5s --health-retries=3"

    postgres-tests:
        name: PostgreSQL
        uses: ./.github/workflows/tests-matrix.yml
        with:
            DATABASE_IMAGE: postgres:17
            DATABASE_PORT: 5432
            DATABASE_USERNAME: postgres
            DATABASE_CONNECTION: pgsql
            DATABASE_OPTIONS: "--health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3"
